### PR TITLE
[HOTFIX#197] Fixed 'Accept Proposal' button that wasn't disabled when the proposal was made by the same user viewing the proposal

### LINKED ISSUE #197: Il pulsante 'Accept Proposal' non è disabilitato, compromette l'UX della pagina di visualizzazione proposta
Come da titolo

### PR DESCRIPTION
**Pull request by alessioarcara**
This PR fixes the bug described in issue #197 and this was causing confusion and negatively impacting the user experience.

### CODE REVIEW

File: src/main/java/com/aadm/cardexchange/client/presenters/ExchangeActivity.java [hunk 1]
```diff
@@ -58,7 +58,7 @@ public void onFailure(Throwable caught) {
             public void onSuccess(ProposalPayload payload) {
                 view.setSenderDeck(false, payload.getSenderCards(), null, payload.getSenderEmail());
                 view.setReceiverDeck(false, payload.getReceiverCards(), null, payload.getReceiverEmail());
-                view.setAcceptButtonEnabled(true);
+                view.setAcceptButtonEnabled(!payload.getSenderEmail().equals(authSubject.getEmail()));
```
Comment (Matte0Sacc0) [inline src/main/java/com/aadm/cardexchange/client/presenters/ExchangeActivity.java:61]: Great to enable the button only for the correct user. This will provide a better UX than giving the feedback to the user after the server response if not allowed to click that button

**Review by dstops — APPROVED** [review]
Good, one less bug!

**Review by Matte0Sacc0 — APPROVED** [review]
As mentioned in the comment: a nice feature to improve UX

**Review by alessiacrimaldi — APPROVED** [review]
